### ISSUE TITLE
Undefined array key 0 with php 8.1 and readonly

### ISSUE THREAD

**Issue by template-provider** [JsonMapper/JsonMapper#145] opened 2022-11-16 10:49 UTC
I have the following classes and test:
```php
<?php

declare(strict_types=1);

namespace JsonMapper\Tests\Implementation\Php81;

class WithConstructorReadOnlyPropertyCollection
{
    /**
     * @param WithConstructorReadOnlyPropertySimple[] $simples
     */
    public function __construct(public readonly array $simples)
    {
    }
}


<?php

declare(strict_types=1);

namespace JsonMapper\Tests\Implementation\Php81;

class WithConstructorReadOnlyPropertySimple
{
    public function __construct(public readonly ?int $status = null)
    {
    }
}


    /**
     * @requires PHP >= 8.1
     */
    public function testCanHandleCustomConstructorsWithEmptyArray(): void
    {
        $factoryRegistry = new FactoryRegistry();
        $mapper = JsonMapperBuilder::new()
            ->withDocBlockAnnotationsMiddleware()
            ->withObjectConstructorMiddleware($factoryRegistry)
            ->withPropertyMapper(new PropertyMapper($factoryRegistry))
            ->build();

        $json = (object) [
            'simples' => [],
        ];

        $result = $mapper->mapToClass($json, WithConstructorReadOnlyPropertyCollection::class);

        self::assertInstanceOf(WithConstructorReadOnlyPropertyCollection::class, $result);
        self::assertIsArray($result->simples);
        self::assertInstanceOf(WithConstructorReadOnlyPropertySimple::class, $result->simples[0]);
    }

```

Basically a collection with items. But the schema allows (and that is ok) empty items.
However I get an "Undefined array key 0" from the default factory, because it assumes a key => value.

fyi ... for me it happened after the update of the php 8.1 but the error is also in the bestfit + without readonly reproducable

**Comment by template-provider** [comment] 2023-01-05 11:52
any updates on this issue?

**Comment by DannyvdSluijs** [comment] 2023-01-06 15:49
@template-provider time and holidays season made me forget these reports. Sorry for that it wasn't my intention to leave you in the dark on it. 
Working on it in https://github.com/JsonMapper/JsonMapper/pull/148

**Comment by DannyvdSluijs** [comment] 2023-01-07 19:48
Merged, will be releasing a new version in a couple of minutes

**Closed by DannyvdSluijs** 2023-01-07 19:48 UTC
Labels: bug

**Comment by aagjalpankaj** [comment] 2023-06-27 19:19
@DannyvdSluijs I was also facing the same error in OMS API. After upgrading, the issue is resolved. Thanks :)
